### ISSUE TITLE
[SUGGESTION] Make a permanent summary issue and edit it's content weekly? 

### ISSUE THREAD

**Issue by BombasticTom** [FunkinCrew/funkin-resources#106]
Instead of having to close a summary issue each week a new one drops, wouldn't it be better if there was a permanently pinned summary issue which would just be edited by the github-actions bot?

I don't really know if this would work, I'm no javascript/workflow expert, I just thought that it could be handy.

**Comment by ninjamuffin99** [comment]
the automatic issue posting for weekly summaries is meant for the funkin.me blog!! our blogging "system" uses github issues as blog posts, so it's meant to be automatically posted issue!! it's not meant for this repo, I just haven't gotten around to setting it up with the other repo yet lol!

**Comment by BombasticTom** [comment]
oh okay my bad
