### ISSUE TITLE
[QUESTION] List of engines

### ISSUE THREAD

**Issue by AltronMaxX** [FunkinCrew/funkin-resources#13]
By what criteria are engines added to [this](https://github.com/FunkinCrew/funkin-resources#engines) list?

**Comment by ninjamuffin99** [comment]
I think if they are generally NOTABLE in some way. Doesn't need to be "famous" or anything, just like, a generally something interesting for people to poke into!

From [The Awesome Manifesto](https://github.com/sindresorhus/awesome/blob/main/awesome.md) 
>try to only include actual awesome stuff in your list. After all, it's a curation, not a collection.

> Research if the stuff you're including is actually awesome. Only put stuff on the list that you or another contributor can personally recommend.

**Comment by BombasticTom** [comment]
i would suggest adding [Kade Engine Fork by BoloVEVO](https://github.com/BoloVEVO/Kade-Engine-Public), i think it's pretty cool.
