### ISSUE TITLE
[QUESTION] Charting related resources

### ISSUE THREAD

**Issue by MarkimusZer0** [FunkinCrew/funkin-resources#19]
A common alternative chart editor i've seen used among FNF charters (myself included) is ArrowVortex (chart editor meant for stepmania mainly) and i was wondering if it'd be worth adding fnf-to-sm (a stepmania chart converter that converts to fnf charts or fnf charts to stepmania charts) as a resource

**Comment by doggogit** [comment]
Being honest, I think *both* deserve to be on the last, as alternatives to the already existing chart editors.

**Comment by BombasticTom** [comment]
agreed

**Comment by doggogit** [comment]
@MarkimusZer0 when you mean fnf-to-sm, do you mean the one that Kade Engine uses, [Kade's fork of fnf-to-sm](https://github.com/KadeDev/fnf-to-sm) or the [original repo](https://github.com/shockdude/fnf-to-sm)?

**Comment by MarkimusZer0** [comment]
> @MarkimusZer0 when you mean fnf-to-sm, do you mean the one that Kade Engine uses, [Kade's fork of fnf-to-sm](https://github.com/KadeDev/fnf-to-sm) or the [original repo](https://github.com/shockdude/fnf-to-sm)?

I mean this os specific versin cau

**Comment by MarkimusZer0** [comment]
> @MarkimusZer0 when you mean fnf-to-sm, do you mean the one that Kade Engine uses, [Kade's fork of fnf-to-sm](https://github.com/KadeDev/fnf-to-sm) or the [original repo](https://github.com/shockdude/fnf-to-sm)?

I mean this specific version cause it works and you can even convert recent psych engine charts by changing one small thing in em
https://github.com/Ashen-Haze/fnf-to-sm

**Comment by MarkimusZer0** [comment]
I mention the Psych Engine thing cause i used to think it was broken and no longer could convert psych charts, but the  i stumbled upon this and now stuff still works perfectly

![Screenshot_20221126-093404-274](https://user-images.githubusercontent.com/73902340/214400657-f111cde2-69f3-4a28-87af-fbe98b62704b.png)

**Comment by MarkimusZer0** [comment]
SectionBeats had broken fnf to sm for the longest time cause of it's inclusion

**Comment by doggogit** [comment]
I see, okay, I'm gonna commit a new charting section to my PR so Cam can review it later and see if it's a good inclusion or not 👍

**Comment by ninjamuffin99** [comment]
ay nice suggestion! I'll add some stuff to get it formatted nicely, I know @PrincessMtH has her own FL Studio charting thing, so would be good to toss in as well!

**Comment by MarkimusZer0** [comment]
> ay nice suggestion! I'll add some stuff to get it formatted nicely, I know @PrincessMtH has her own FL Studio charting thing, so would be good to toss in as well!

Will def include MtH's thing as well!!
Though I'm prob gon wait till the overhaul pr gets accepted to not cause any conflicts with it

**Comment by doggogit** [comment]
Will add it for you :D

**Comment by ninjamuffin99** [comment]
solved with #16
