### ISSUE TITLE
Funkin' Bounties suggestions?

### ISSUE THREAD

**Issue by ninjamuffin99** [FunkinCrew/funkin-resources#24]
we have the funkin bounties repo that we will use for various ez lil paid work that we can toss to anyone, and I think it'd be a nice resource for people to keep an eye on. Should it be in `Programming`? a section dedicated to our `Funkin' Crew` related stuff?

https://github.com/FunkinCrew/funkinBounties

**Comment by doggogit** [comment]
Yeah, sounds about right

It already has [11 watchers](https://github.com/FunkinCrew/funkinBounties/watchers), but there could always be more! >:)

**Comment by MarkimusZer0** [comment]
Yea definitely, would be a good resource to folks who feel up to helping out the Funkin' Team and even getting some cash for it

**Comment by EliteMasterEric** [comment]
Added to the programming section
