### ISSUE TITLE
Add VinceS’ tutorials on chromatic scales and sampling for them

### ISSUE THREAD

**Issue by DobtAWESOME** [FunkinCrew/funkin-resources#38]
https://youtu.be/D4jWnvAEkhk
https://youtu.be/JzKr6xFAWMA

both are easy to understand, and some of the best methods for chromatic scaling

**Comment by doggogit** [comment]
You can open a Pull Request and add those to the Chromatic Scale Guides section of the README

**Comment by doggogit** [comment]
This should be closed as its mentioned in #46.

**Comment by EliteMasterEric** [comment]
Yep
