### ISSUE TITLE
MENTION KADE RIGHT NOW!!!1!!1!1

### ISSUE THREAD

**Issue by AbaFunni** [FunkinCrew/funkin-resources#39]
hear me out
ik psych carried MODERN era of this community but kade has been used so many times before by so many cool people in this community
it may be outdated sure but it's still a good engine!!!
i'd recommend the BOLO kade fork, or even just the original one!

**Comment by BombasticTom** [comment]
i was thinking of making a commit for bolovevo's ke fork, but if you have been paying attention, mastereric said that kade engine won't be accepted cuz it's deprecated (it's active forks will probably be added tho).

**Comment by doggogit** [comment]
As Tom said, Kade's original repository won't be added as its been depreciated for almost a fucking year now. Maybe Bolo's Kade fork will make it in.

**Comment by BombasticTom** [comment]
making a pull request with sum additional stuff right now

**Comment by EliteMasterEric** [comment]
I concluded that Kade's original repo is notable enough to include, albeit with a deprecation warning.
