### ISSUE TITLE
Include free DAWs for those who can't afford FL Studio or Ableton Live?

### ISSUE THREAD

**Issue by SmeckoGeck46** [FunkinCrew/funkin-resources#40]
This is a really nice resource list for those who wanna get into modding FNF.

Something I would like to suggest is a subcategory for the "Composing" category on free DAWs for anyone who can't afford FL Studio or Ableton Live yet (or don't want to pirate them). I've been using free DAWs for making music since 2019, so I've got some experience.

These are some of the free DAWs I've used before:
LMMS: https://lmms.io/
SoundBridge: https://soundbridge.io/
Cakewalk by Bandlab (note: this DAW is Windows-only): https://www.bandlab.com/products/cakewalk
Waveform Free: https://www.tracktion.com/products/waveform-free

I've also used GarageBand for making music (specifically the desktop version), but that's built-in to Mac computers.

**Comment by BombasticTom** [comment]
good idea 👍

**Comment by EliteMasterEric** [comment]
Once you have a good list together please prepare a pull request

**Comment by SmeckoGeck46** [comment]
Pull request made. Hopefully, it gets submitted.

**Comment by EliteMasterEric** [comment]
merged 39 minutes ago
