### ISSUE TITLE
[QUESTION] Reorganize way of how the engines category works?

### ISSUE THREAD

**Issue by BombasticTom** [FunkinCrew/funkin-resources#43]
The markdown snippet shown below is what I had in mind:

* * *

### Engines
- [Friday Night Funkin'](https://github.com/FunkinCrew/funkin) - The original open source game by The Funkin' Crew.
- #### Base Game Modifications:
  - [Psych Engine](https://github.com/ShadowMario/FNF-PsychEngine) - A fork of base game which includes new quality-of-life changes, performance improvements, and Lua-based mod tools. Popular and well-documented. 
  - [Forever Engine](https://github.com/BeastlyGabi/Funkin-Forever-Engine) - An archived rewrite of the game, originally written by Yoshubs. Includes performance reworks, HScript support, and more.
    - [Forever Engine Feather](https://github.com/Pluma-Team/Forever-Engine-Feather) - A fork of Forever Engine, that includes all of its features, a scripting system based on HScript, called SScript, reorganized codebase, an events system based off of Hypno's Lullaby v2 and fully softcoded weeks and characters. 
  - etc...
- #### Mobile Ports:
  - [Funkin' Android](https://github.com/luckydog7/Funkin-android) - A fork of the game with controls and optimizations allowing it to be played on Android devices.
  - [FunkiniOS](https://github.com/hadobedo/FunkiniOS) - A port of FNF to iOS devices, requires sideloading (thank god for the EU regulations)
- #### Game Ports:
  - [PSXFunkin](https://github.com/cuckydev/PSXFunkin) - A Playstation 1 de-make in C/C++
  - [FNF LÖVE](https://github.com/Stilic/FNF-LOVE) - A Lua recreation of FNF within the LÖVE2D engine.
  - [FNF-Benjine](https://github.com/this-is-bennyk/FNF-Benjine) - Funkin' but in Godot, made by [BennyK](https://github.com/this-is-bennyk) and was used for [Funkin' VR](https://github.com/this-is-bennyk/Funkin-VR).

* * *
I thought it might be an unnecessary change, so that's why I opened this issue as a question.

**Comment by BombasticTom** [comment]
I could do it too, it's not a big deal. But I thought it would be better to see if The Funkin Crew approves the change before actually doing something, kind of time saving for doing something else in the day (lol).

**Comment by doggogit** [comment]
True true

**Comment by ninjamuffin99** [comment]
this looks good amen

**Comment by EliteMasterEric** [comment]
I ended up reorganizing the engine list myself. If you want to do any more cleanup feel free to make a new issue or a pull request.

**Comment by BombasticTom** [comment]
> I ended up reorganizing the engine list myself. If you want to do any more cleanup feel free to make a new issue or a pull request.

All right, will see 👍

**Comment by BombasticTom** [comment]
to be honest i really like your version, so i'll just fix the contents thing being broken
