### ISSUE TITLE
Regarding engine forks and whatnot

### ISSUE THREAD

**Issue by doggogit** [FunkinCrew/funkin-resources#44]
Alright, I believe we should be a little harsh when it comes to engine forks.

**Any engine forks that include not that many QoL changes, have miscellaneous changes (like a new HUD) that can be made with a script within 5 to 10 minutes, should be automatically rejected**.

There are, obviously, exception, for example: [the Raltyro Psych Fork](https://github.com/Raltyro/FNF-PsikeEngine), [Pluma's Psych Fork](https://github.com/Pluma-Team/FNF-PsychEngine-Pluma) and others that I can't think of at the top of my head.

(feel free to pin this btw)

**Comment by BombasticTom** [comment]
[Custom Psych Engine](https://github.com/BombasticTom/Custom-Psych-Engine) too!!

(this is a joke, it doesn't have any progress, and there's a newer version in works which i've stopped working on months ago)

**Comment by ninjamuffin99** [comment]
more or less i think. if someone looks at the changes, and they dont think they are super incredible awesome or interesting , can be rejected

**Comment by Burgerballs** [comment]
Most of the stuff they add (specifically psych forks) are already replicated in lua by the base Psych community too.

**Comment by BombasticTom** [comment]
damn, didn't know that. the only fork i know of (os engine) changes some menu stuff and adds new options (that i personally think are too much)

**Comment by Burgerballs** [comment]
> damn, didn't know that. the only fork i know of (os engine) changes some menu stuff and adds new options (that i personally think are too much)

I checked the os engine readme and yeah all of the OS Engine features (other than the menus) can be recreated in base Psych 0.6.3, including shaders lol

**Comment by BombasticTom** [comment]
There's a lot of psych ports just using lua scripts (lmao)

**Comment by Burgerballs** [comment]
> There's a lot of psych ports just using lua scripts (lmao)

Most of them aren't theirs either too

**Comment by doggogit** [comment]
> more or less i think. if someone looks at the changes, and they dont think they are super incredible awesome or interesting , can be rejected

I feel like a section related to this should be added to the Code of Conduct file

**Comment by Burgerballs** [comment]
> > more or less i think. if someone looks at the changes, and they dont think they are super incredible awesome or interesting , can be rejected
> 
> I feel like a section related to this should be added to the Code of Conduct file

https://github.com/sindresorhus/awesome/blob/main/awesome.md
"Research if the stuff you're including is actually awesome."

**Comment by doggogit** [comment]
> > > more or less i think. if someone looks at the changes, and they dont think they are super incredible awesome or interesting , can be rejected
> > 
> > 
> > I feel like a section related to this should be added to the Code of Conduct file
> 
> https://github.com/sindresorhus/awesome/blob/main/awesome.md "Research if the stuff you're including is actually awesome."

Only a suggestion, but fair enough, should've probably read the manifesto and stuff lol

**Comment by doggogit** [comment]
Should this issue be closed? I don't really know where to take this discussion from here, this was just for raising awareness, not gonna lie. It can be a pinned issue if possible.

**Comment by BombasticTom** [comment]
i think that the pinned issue should be the first one made (the Add Descriptions To Links? one)

**Comment by BombasticTom** [comment]
oh well lol

**Comment by doggogit** [comment]
Closing this as #51 resolves this issue.
