### ISSUE TITLE
[QUESTION] Is Crow Engine a rewrite or an engine of it's own?

### ISSUE THREAD

**Issue by EyeDaleHim** [FunkinCrew/funkin-resources#58]
My engine is a WIP rewrite of the game, meaning all the code is mostly built from scratch, is this considered a rewrite of the game and should be put into the "Rewrite/Ports" category or will it stay as is?

**Comment by BombasticTom** [comment]
im pretty sure that the rewrites thing means rewrite in another language

**Comment by BombasticTom** [comment]
cuz if it was for rewrites, FE would've been counted too

**Comment by EyeDaleHim** [comment]
Alright, Crow Engine dosen't count as a rewrite due to Forever Engine most likely.

**Comment by EliteMasterEric** [comment]
I put anything HaxeFlixel (even rewrites) in the Engines category.

If it's not Haxe it goes in the Rewrites category.

If it's Haxe but not Flixel (so Heaps or Kha) I'd... also put it under rewrites.

**Comment by BombasticTom** [comment]
> I put anything HaxeFlixel (even rewrites) in the Engines category.
> 
> If it's not Haxe it goes in the Rewrites category.
> 
> If it's Haxe but not Flixel (so Heaps or Kha) I'd... also put it under rewrites.

Maybe this should be an annoucement for people who don't know this (when making a pr) ?
