### ISSUE TITLE
[QUESTION] Link this resource page to the Funk Blog site?

### ISSUE THREAD

**Issue by BombasticTom** [FunkinCrew/funkin-resources#60]
here's an image of how the redirect link could look like:

<img src="https://user-images.githubusercontent.com/85838311/214874797-33bef56b-34e4-4a34-a2ac-07ef0cd7e972.png" alt="a" width=75%/>

the link would also redirect the user to a blog-looking page, which would look similarly to this image (that i photoshopped in a few mins lol):
![image](https://user-images.githubusercontent.com/85838311/214876463-56575528-4bdd-4b0c-a287-9f5d1cb7eccd.png)
you could also try to update the page using queueing system you have been talking about (idk if it's possible tho cuz i don't know how it works!!)

i think this can work nicely for people who want to find all of the game information on the official site.

**Comment by MarkimusZer0** [comment]
Isn't the blog already in the resource

**Comment by BombasticTom** [comment]
did you look at the images

**Comment by MarkimusZer0** [comment]
Yeah I'm still confused

**Comment by BombasticTom** [comment]
imagine if there was a blog post that's basically this README.md file

**Comment by doggogit** [comment]
I actually like this a shit ton

**Comment by ninjamuffin99** [comment]
Will do! Will close when tomorrows blog post comes out!

**Comment by ninjamuffin99** [comment]
closed with https://github.com/FunkinCrew/funkBlog/commit/661a159679366ab42f6e432ce3cb8d687ca56840

**Comment by BombasticTom** [comment]
sweet
